const responses = {
    "descricao": {
            "o que você pode fazer?": "Sou o GMR, uma inteligência artificial local e offline criada por Gabriel Menezes Rehbein. Aqui está o que eu posso fazer:\n" +
                "1. **Respostas gerais**: Respondo perguntas sobre curiosidades, história, ciência, geografia e mais.\n" +
                "2. **Suporte técnico**: Ajudar com tarefas como formatação de pendrives, limpeza de computador, instalação de programas e resolução de problemas técnicos.\n" +
                "3. **Cálculos matemáticos**: Realizar cálculos básicos (soma, subtração, multiplicação, divisão) e avançados (logaritmos, trigonometria, exponenciais).\n" +
                "4. **Geometria e Finanças**: Calcular áreas, perímetros, juros simples e compostos, além de oferecer dicas de planejamento financeiro.\n" +
                "5. **Curiosidades e Cultura**: Respondo perguntas sobre temas gerais, como mitologia, capital de países, invenções históricas e mais.\n" +
                "6. **Interação divertida**: Conto piadas, faço perguntas interessantes e respondo de forma descontraída.\n" +
                "7. **Dicas de produtividade e desenvolvimento pessoal**: Sugestões práticas para organização, otimização do tempo e construção de hábitos saudáveis.\n" +
                "8. **Saúde e bem-estar**: Dou dicas sobre saúde pública, alimentação equilibrada, prevenção de doenças e bem-estar mental.\n" +
                "9. **Tecnologia e inovação**: Explico conceitos como inteligência artificial, blockchain, nanotecnologia, energia renovável, entre outros.\n" +
                "10. **História e Educação**: Falo sobre grandes eventos históricos, figuras marcantes, modelos educacionais e gamificação no aprendizado.\n" +
                "11. **Ciência e Natureza**: Explico fenômenos naturais, avanços científicos, biodiversidade e sustentabilidade.\n" +
                "12. **Exploração espacial e astronomia**: Respondo perguntas sobre planetas, estrelas, satélites e tecnologia espacial.\n" +
                "13. **Cultura pop e entretenimento**: Discuto sobre filmes, música, literatura, animes e personagens icônicos.\n" +
                "14. **Totalmente Offline**: Funciono sem internet, diretamente do seu computador, oferecendo conhecimento e auxílio a qualquer momento.\n\n" +
                "Pergunte algo ou peça ajuda, estou aqui para facilitar sua vida!"
        },
        "saudacoes": {
                "olá": "Olá! Sou o GMR, seu assistente local. Como posso ajudar hoje?",
                "oi": "Oi! Tudo bem? Como posso ajudar você?",
                "e aí": "E aí! Tudo certo? Precisa de algo?",
                "bom dia": "Bom dia! Espero que você tenha um dia incrível.",
                "boa tarde": "Boa tarde! O que está precisando hoje?",
                "boa noite": "Boa noite! Estou por aqui se precisar de algo.",
                "oi, tudo bem?": "Tudo ótimo, obrigado por perguntar! Como posso ajudar você?",
                "como vai?": "Vou muito bem, obrigado! E você, como está?",
                "tudo certo?": "Tudo certo por aqui! Em que posso ajudar você?",
                "fala aí": "Fala! O que você precisa hoje?",
                "saudações": "Saudações! Pronto para ajudar em qualquer coisa que você precise.",
                "opa": "Opa! Tudo bem por aí? Como posso ajudar?",
                "salve": "Salve! O que manda?",
                "como está?": "Estou ótimo, obrigado! E você, como está se sentindo hoje?",
                "oi, você está aí?": "Sim, sempre por aqui! O que você precisa?",
                "oi, bom dia": "Bom dia! O que você gostaria de saber ou fazer hoje?",
                "oi, boa tarde": "Boa tarde! Em que posso ser útil agora?",
                "oi, boa noite": "Boa noite! Espero que você esteja bem. Como posso ajudar?",
                "e aí, como vai?": "Estou ótimo, obrigado por perguntar! Como está você?",
                "oi, tá tudo bem?": "Sim, tudo em ordem! E com você?",
                "oi oi": "Oi, oi! Animado para te ajudar!",
                "alô": "Alô! Estou aqui, o que posso fazer por você?",
                "hey": "Hey! Tudo certo por aí? Em que posso ajudar?",
                "bom dia, como você está?": "Bom dia! Estou ótimo, e espero que você também esteja.",
                "boa tarde, tudo bem?": "Boa tarde! Tudo ótimo por aqui. O que você precisa?",
                "boa noite, como vai?": "Boa noite! Tudo tranquilo por aqui. O que você gostaria de saber?",
                "oi, tudo certo?": "Tudo certinho! Como posso ajudar você agora?",
                "olá, como posso te ajudar?": "Olá! Pronto para responder qualquer pergunta ou ajudar em algo.",
                "e aí, gmr?": "E aí! O que posso fazer por você?",
                "bom dia, gmr": "Bom dia! Espero que seu dia esteja sendo incrível. Precisa de algo?",
            },
            "historia": {
                "quem foi dom pedro ii?": "Dom Pedro II foi o segundo e último imperador do Brasil, governando de 1831 a 1889.",
                "o que foi a revolução francesa?": "Foi um movimento político e social na França entre 1789 e 1799, resultando no fim da monarquia absoluta e no surgimento de uma república.",
                "quem descobriu o brasil?": "O Brasil foi oficialmente descoberto por Pedro Álvares Cabral em 22 de abril de 1500.",
                "quando começou a segunda guerra mundial?": "A Segunda Guerra Mundial começou em 1º de setembro de 1939.",
                "o que foi o renascimento?": "Foi um movimento cultural e artístico na Europa no século XIV, marcando a transição da Idade Média para a Idade Moderna.",
            },
            "ciencia": {
                "o que é o efeito estufa?": "É um fenômeno natural em que gases na atmosfera aprisionam o calor do Sol, mantendo a Terra aquecida.",
                "qual é o elemento químico mais abundante no universo?": "O hidrogênio é o elemento mais abundante no universo.",
                "como as estrelas nascem?": "Elas nascem em nebulosas, onde a gravidade faz o gás colapsar até iniciar a fusão nuclear.",
                "o que é um átomo?": "O átomo é a menor unidade básica de um elemento químico, composto por prótons, nêutrons e elétrons.",
                "quem formulou a teoria da evolução?": "A teoria da evolução foi formulada por Charles Darwin no século XIX.",
            },
            "musica_e_entretenimento": {
                "qual é a música mais ouvida no mundo?": "Isso varia com o tempo, mas 'Blinding Lights' do The Weeknd é uma das músicas mais reproduzidas recentemente.",
                "quem foi beethoven?": "Beethoven foi um compositor alemão de música clássica, famoso por sinfonias como a 5ª e a 9ª.",
                "o que é um gênero musical?": "É uma categorização de música baseada em ritmo, instrumentação e estilo vocal.",
                "quais são os instrumentos de corda?": "Violão, guitarra, violino, violoncelo, harpa, entre outros.",
                "quem ganhou o oscar de melhor filme em 2023?": "Depende do contexto. Verifique os vencedores mais recentes para atualizações.",
            },
            "alimentacao_e_receitas": {
                "como fazer um bolo simples?": "Misture 3 ovos, 1 xícara de açúcar, 2 xícaras de farinha, 1/2 xícara de óleo, 1 xícara de leite e 1 colher de fermento. Asse por 30 minutos a 180°C.",
                "o que é uma dieta balanceada?": "Inclui proteínas, carboidratos, gorduras saudáveis, fibras, vitaminas e minerais em proporções adequadas.",
                "como cozinhar arroz?": "Refogue o arroz, adicione o dobro de água e cozinhe em fogo baixo até a água secar.",
                "quais frutas são ricas em vitamina c?": "Laranja, limão, acerola, kiwi e morango.",
                "o que são proteínas?": "São macronutrientes essenciais encontrados em alimentos como carne, ovos, leite e leguminosas.",
            },
            "saude": {
                "quantas horas de sono são recomendadas?": "Adultos geralmente precisam de 7 a 9 horas de sono por noite.",
                "o que é hipertensão?": "É uma condição onde a pressão arterial está consistentemente elevada.",
                "como melhorar a imunidade?": "Durma bem, pratique exercícios, mantenha uma alimentação balanceada e evite estresse.",
                "o que é um vírus?": "É um agente infeccioso microscópico que só pode se reproduzir dentro de uma célula hospedeira.",
                "como aliviar dores de cabeça?": "Hidrate-se, descanse em um ambiente calmo e, se necessário, tome um analgésico.",
            },
            "literatura": {
                "quem escreveu 'dom casmurro'?": "Machado de Assis escreveu 'Dom Casmurro', um clássico da literatura brasileira.",
                "o que é um poema?": "É uma forma de expressão literária que utiliza palavras em formas rítmicas e estilizadas.",
                "qual é o livro mais vendido de todos os tempos?": "A Bíblia é o livro mais vendido de todos os tempos.",
                "o que é um conto?": "É uma narrativa breve focada em um único evento ou personagem.",
                "quem foi shakespeare?": "William Shakespeare foi um dramaturgo e poeta inglês, autor de 'Romeu e Julieta' e 'Hamlet'.",
            },
            "clima_e_meio_ambiente": {
                "o que é aquecimento global?": "É o aumento da temperatura média da Terra devido à emissão de gases do efeito estufa.",
                "como prever o tempo?": "Utiliza dados de satélites, estações meteorológicas e modelos matemáticos.",
                "o que são energias renováveis?": "São fontes de energia que se renovam naturalmente, como solar, eólica e hidroelétrica.",
                "por que as folhas são verdes?": "Por causa da clorofila, um pigmento que absorve luz solar para a fotossíntese.",
                "o que é desmatamento?": "É a remoção de florestas, geralmente para agricultura ou urbanização, causando impacto ambiental.",
            },
            "tecnologia_avancada": {
                "o que é blockchain?": "É uma tecnologia que registra transações de forma descentralizada, segura e transparente.",
                "o que é iot?": "Internet das Coisas (IoT) é a interconexão de dispositivos pela internet, permitindo comunicação e automação.",
                "o que é um data center?": "É uma instalação que abriga servidores e sistemas para armazenar e gerenciar dados.",
                "o que é realidade aumentada?": "É uma tecnologia que sobrepõe elementos virtuais ao mundo real por meio de dispositivos especiais.",
                "como funcionam drones?": "Drones são controlados remotamente e usam motores, giroscópios e sensores para voar.",
            },
            "economia": {
                "o que é inflação?": "Inflação é o aumento geral dos preços de bens e serviços ao longo do tempo.",
                "o que é pib?": "Produto Interno Bruto (PIB) é o valor total de bens e serviços produzidos em um país.",
                "como economizar dinheiro?": "Estabeleça um orçamento, evite compras por impulso e invista uma parte da sua renda.",
                "o que são criptomoedas?": "São moedas digitais descentralizadas, como Bitcoin, usadas para transações e investimentos.",
                "como funciona o mercado de ações?": "Empresas vendem ações para investidores que lucram com valorização ou dividendos.",
            },
            "esportes": {
                "qual é o esporte mais popular do mundo?": "O futebol é o esporte mais popular, com bilhões de fãs ao redor do mundo.",
                "quem é pelé?": "Pelé é considerado um dos maiores jogadores de futebol de todos os tempos e venceu três Copas do Mundo pelo Brasil.",
                "o que é um grand slam no tênis?": "É o título dado aos torneios mais prestigiados do tênis: Australian Open, Roland Garros, Wimbledon e US Open.",
                "quantos jogadores tem um time de basquete?": "Cada time tem 5 jogadores em quadra durante uma partida oficial.",
                "qual é o esporte mais antigo do mundo?": "A luta livre é considerada o esporte mais antigo, com evidências em pinturas rupestres.",
            },
            "filosofia": {
                "quem foi sócrates?": "Sócrates foi um filósofo grego que é considerado o pai da filosofia ocidental.",
                "o que é o existencialismo?": "É uma corrente filosófica que enfatiza a liberdade e a responsabilidade individual.",
                "quem disse 'penso, logo existo'?": "René Descartes, um filósofo francês.",
                "o que é ética?": "É o estudo dos princípios que governam o comportamento humano.",
                "o que é a filosofia estoica?": "É uma filosofia que ensina a importância da resiliência e do autocontrole para enfrentar os desafios da vida.",
            },
            "cultura_diferentes_paises": {
                "qual é o prato típico do japão?": "Sushi é um dos pratos mais conhecidos da culinária japonesa.",
                "qual é a dança típica da argentina?": "O tango é a dança tradicional da Argentina.",
                "o que é oktoberfest?": "É um festival de cerveja originado na Alemanha, celebrado anualmente.",
                "qual é o maior deserto do mundo?": "O Saara é o maior deserto quente do mundo, localizado na África.",
                "quais idiomas são falados na suíça?": "Alemão, francês, italiano e romanche.",
            },
            "educacao": {
                "o que é alfabetização?": "É o processo de aprender a ler e escrever.",
                "quais são as principais matérias escolares?": "Matemática, português, ciências, história e geografia.",
                "o que é ensino superior?": "É a educação oferecida por universidades e faculdades após o ensino médio.",
                "qual é a diferença entre mestrado e doutorado?": "O mestrado é um grau acadêmico de nível avançado, enquanto o doutorado é o nível mais alto de formação acadêmica.",
                "como aprender um novo idioma?": "Pratique diariamente, ouça músicas, assista filmes no idioma e tente conversar com nativos.",
            },
            "carreiras_profissionais": {
                "o que faz um engenheiro?": "Um engenheiro projeta, desenvolve e mantém sistemas e estruturas em diversas áreas, como civil, elétrica e mecânica.",
                "como escolher uma profissão?": "Identifique suas paixões, habilidades e o mercado de trabalho na sua área de interesse.",
                "o que é um freelancer?": "É um profissional autônomo que trabalha por conta própria, sem vínculo fixo com empresas.",
                "qual é o papel de um gerente de projetos?": "Gerenciar recursos, prazos e equipes para garantir o sucesso de um projeto.",
                "o que é um estágio?": "É uma experiência prática em uma empresa ou organização para adquirir conhecimentos em uma área profissional.",
            },
            "psicologia": {
                "o que é ansiedade?": "Ansiedade é uma sensação de preocupação ou medo em resposta a situações futuras.",
                "o que é autoestima?": "É a percepção que uma pessoa tem de seu próprio valor e habilidades.",
                "o que faz um psicólogo?": "Um psicólogo ajuda as pessoas a lidar com questões emocionais, comportamentais e sociais.",
                "como lidar com o estresse?": "Pratique exercícios físicos, meditação, respiração profunda e busque apoio emocional.",
                "o que é depressão?": "É um transtorno mental caracterizado por tristeza persistente, perda de interesse e baixa energia.",
            },
            "astronomia": {
                "o que é um planeta?": "Um planeta é um corpo celeste que orbita uma estrela, tem massa suficiente para ser esférico e limpa sua órbita de detritos.",
                "o que é um cometa?": "Um cometa é um corpo celeste feito de gelo, poeira e rochas que deixa uma cauda luminosa ao passar perto do Sol.",
                "qual é a maior estrela do universo?": "A UY Scuti é uma das maiores estrelas conhecidas.",
                "quantos satélites naturais a terra tem?": "A Terra tem um único satélite natural: a Lua.",
                "o que são constelações?": "São grupos de estrelas que formam padrões no céu.",
            },
            "geografia": {
                "qual é o maior país do mundo?": "A Rússia é o maior país do mundo em área territorial.",
                "o que é uma ilha?": "Uma ilha é uma porção de terra cercada por água em todos os lados.",
                "quais são os oceanos do mundo?": "Pacífico, Atlântico, Índico, Ártico e Antártico.",
                "qual é a montanha mais alta do mundo?": "O Monte Everest, com 8.848 metros de altura.",
                "o que é o círculo polar ártico?": "É uma região localizada no extremo norte do planeta, dentro do Ártico.",
            },
            "religiao": {
                "o que é o cristianismo?": "É uma religião baseada nos ensinamentos de Jesus Cristo.",
                "quem é buda?": "Buda é o fundador do budismo, uma religião e filosofia baseada na busca pela iluminação.",
                "quantos livros tem a bíblia?": "A Bíblia cristã possui 66 livros (na versão protestante) ou 73 livros (na versão católica).",
                "o que é o alcorão?": "O Alcorão é o livro sagrado do Islã.",
                "o que é hinduísmo?": "É uma das religiões mais antigas do mundo, originada na Índia, com crenças em reencarnação e múltiplos deuses.",
            },
            "tecnologia_e_inovacao": {
                "o que é inteligência artificial?": "É um campo da ciência que cria máquinas capazes de realizar tarefas que exigem inteligência humana.",
                "o que é um algoritmo?": "É uma sequência de passos lógicos para resolver um problema ou realizar uma tarefa.",
                "qual é a função de uma placa-mãe?": "Ela conecta todos os componentes de um computador, permitindo que trabalhem juntos.",
                "o que são redes neurais?": "São modelos computacionais inspirados no cérebro humano, usados em inteligência artificial.",
                "o que é um processador?": "É o cérebro de um computador, responsável por executar instruções e processar dados.",
            },
            "animais": {
                "qual é o animal mais rápido do mundo?": "O falcão-peregrino é o animal mais rápido, podendo atingir velocidades de até 390 km/h em mergulho.",
                "quantos corações tem um polvo?": "Um polvo tem três corações.",
                "o que é um animal carnívoro?": "É um animal que se alimenta predominantemente de carne.",
                "qual é o maior mamífero terrestre?": "O elefante africano é o maior mamífero terrestre.",
                "qual é a diferença entre crocodilo e jacaré?": "Os crocodilos têm focinhos mais finos e vivem em água salgada e doce, enquanto os jacarés preferem água doce e têm focinhos mais largos.",
            },
            "curiosidades": {
                "o que é a muralha da china?": "É uma série de fortificações construídas ao longo de séculos para proteger a China de invasões.",
                "o que é o triângulo das bermudas?": "É uma área do Oceano Atlântico onde supostamente ocorrem desaparecimentos misteriosos de navios e aviões.",
                "quem inventou a internet?": "A internet foi desenvolvida por cientistas como Vint Cerf e Bob Kahn nos anos 1970.",
                "quantas línguas existem no mundo?": "Existem cerca de 7.000 idiomas falados no mundo atualmente.",
                "qual é a cidade mais populosa do mundo?": "Tóquio, no Japão, é a cidade mais populosa do mundo, com mais de 37 milhões de habitantes na região metropolitana.",
            },
            "medicina": {
                "o que é hipertensão?": "É uma condição em que a pressão arterial está constantemente elevada.",
                "como tratar uma febre?": "Hidrate-se, descanse e use medicamentos antitérmicos, se necessário. Consulte um médico se a febre persistir.",
                "o que é vacina?": "Uma vacina é uma substância que estimula o sistema imunológico a produzir imunidade contra doenças.",
                "o que é diabetes?": "É uma doença crônica em que o corpo tem dificuldade em regular os níveis de açúcar no sangue.",
                "o que é um vírus?": "Um vírus é um microorganismo infeccioso que precisa de uma célula hospedeira para se reproduzir.",
            },
            "mitologia": {
                "quem é zeus?": "Zeus é o deus do trovão e líder dos deuses na mitologia grega.",
                "o que é o valhala?": "Valhala é o paraíso dos guerreiros na mitologia nórdica, onde os mortos em combate são recebidos por Odin.",
                "quem é anúbis?": "Anúbis é o deus egípcio dos mortos e da mumificação.",
                "quem é thor?": "Thor é o deus do trovão na mitologia nórdica, conhecido por seu martelo Mjölnir.",
                "o que é a caixa de pandora?": "Na mitologia grega, é um artefato que, quando aberto, liberou todos os males no mundo.",
            },
            "arte": {
                "quem pintou a mona lisa?": "Leonardo da Vinci pintou a Mona Lisa.",
                "o que é o renascimento artístico?": "Foi um movimento cultural que ocorreu na Europa entre os séculos XIV e XVII, marcado por avanços na arte e ciência.",
                "o que é cubismo?": "Cubismo é um movimento artístico que usa formas geométricas para representar objetos e figuras.",
                "quem foi vincent van gogh?": "Van Gogh foi um pintor holandês famoso por obras como 'Noite Estrelada' e 'Girassóis'.",
                "o que é uma escultura?": "Escultura é uma forma de arte tridimensional feita de materiais como pedra, metal ou madeira.",
            },
            "tecnologia": {
                "o que é realidade virtual?": "É uma tecnologia que simula ambientes digitais tridimensionais, permitindo interação por meio de dispositivos como óculos VR.",
                "o que é big data?": "É um conjunto de dados extremamente grandes e complexos, analisados para revelar padrões e tendências.",
                "o que é 5g?": "5G é a quinta geração de redes móveis, oferecendo maior velocidade e menor latência.",
                "como funciona uma impressora 3d?": "Ela cria objetos tridimensionais camada por camada, a partir de um modelo digital.",
                "o que é cibersegurança?": "Cibersegurança é a proteção de sistemas e redes contra ataques digitais.",
            },
            "clima": {
                "o que é um furacão?": "É uma tempestade tropical com ventos intensos, geralmente formados em oceanos quentes.",
                "o que é o efeito de ilha de calor?": "É o aumento da temperatura em áreas urbanas devido à substituição de vegetação por concreto e asfalto.",
                "o que são chuvas ácidas?": "Chuvas ácidas ocorrem quando poluentes no ar, como dióxido de enxofre, se misturam com a água da chuva.",
                "o que é um arco-íris?": "É um fenômeno óptico causado pela refração, dispersão e reflexão da luz em gotas de água.",
                "o que é um tsunami?": "É uma série de ondas gigantescas causadas por terremotos ou erupções vulcânicas no oceano.",
            },
            "historia_modernidade": {
                "o que foi a guerra fria?": "Foi um período de tensão geopolítica entre os Estados Unidos e a União Soviética, que durou de 1947 a 1991.",
                "o que foi o 11 de setembro?": "Foi um ataque terrorista nos Estados Unidos em 2001, em que aviões sequestrados colidiram com o World Trade Center.",
                "quem foi nelson mandela?": "Nelson Mandela foi um líder sul-africano que lutou contra o apartheid e se tornou o primeiro presidente negro da África do Sul.",
                "o que foi a revolução industrial?": "Foi um período entre os séculos XVIII e XIX marcado pela transição de métodos de produção artesanais para industriais.",
                "quem foi mahatma gandhi?": "Gandhi foi um líder indiano que usou a resistência pacífica para lutar pela independência da Índia.",
            },
            "linguagem_programacao": {
                "o que é python?": "Python é uma linguagem de programação de alto nível, conhecida por sua simplicidade e versatilidade.",
                "o que é javascript?": "JavaScript é uma linguagem de programação usada principalmente para desenvolvimento web, adicionando interatividade às páginas.",
                "o que é uma variável?": "É um espaço na memória usado para armazenar dados que podem mudar durante a execução do programa.",
                "o que é um loop?": "Um loop é uma estrutura de controle que repete um bloco de código enquanto uma condição for verdadeira.",
                "o que é uma função?": "É um bloco de código reutilizável que realiza uma tarefa específica e pode ser chamado pelo nome.",
            },
            "internet": {
                "o que é uma URL?": "URL significa Uniform Resource Locator e é o endereço de um recurso na internet.",
                "o que é HTTP?": "HTTP significa HyperText Transfer Protocol e é o protocolo usado para transferir dados na web.",
                "o que é um navegador?": "É um software usado para acessar e visualizar páginas na internet, como Chrome, Firefox ou Edge.",
                "o que é um servidor?": "É um computador ou programa que fornece serviços ou dados a outros computadores na rede.",
                "o que é um cookie?": "Cookies são pequenos arquivos armazenados no navegador para salvar informações sobre a navegação do usuário.",
            },
            "curiosidades_historicas": {
                "quem foi cleópatra?": "Cleópatra foi a última faraó do Egito, conhecida por sua inteligência e alianças políticas com Roma.",
                "o que é a grande pirâmide de gizé?": "É a maior das pirâmides do Egito e uma das Sete Maravilhas do Mundo Antigo ainda existente.",
                "o que foi a peste negra?": "A peste negra foi uma pandemia que matou milhões de pessoas na Europa durante o século XIV.",
                "quem foi genghis khan?": "Genghis Khan foi o fundador do Império Mongol, que se tornou o maior império contíguo da história.",
                "o que é a pedra de roseta?": "É um artefato que ajudou os arqueólogos a decifrar os hieróglifos egípcios.",
            },
            "negocios_e_investimentos": {
                "o que é uma startup?": "Uma startup é uma empresa jovem que busca resolver problemas usando modelos de negócios inovadores.",
                "o que é um IPO?": "IPO significa Initial Public Offering, que é quando uma empresa vende ações ao público pela primeira vez.",
                "o que é um dividendo?": "Dividendo é uma parte do lucro de uma empresa distribuída aos acionistas.",
                "o que é a bolsa de valores?": "É um mercado onde ações de empresas são compradas e vendidas.",
                "como funciona um fundo de investimento?": "É uma forma coletiva de investimento onde várias pessoas aplicam dinheiro em um portfólio gerido por especialistas.",
            },
            "inteligencia_artificial": {
                "o que é machine learning?": "Machine learning é uma área da IA que ensina máquinas a aprenderem padrões a partir de dados.",
                "o que é deep learning?": "É um subcampo de machine learning que utiliza redes neurais profundas para processar dados complexos.",
                "o que é processamento de linguagem natural?": "É uma área da IA que lida com a interação entre computadores e linguagem humana.",
                "o que são redes neurais artificiais?": "São sistemas computacionais inspirados no cérebro humano, usados para aprendizado e processamento de dados.",
                "o que é visão computacional?": "É o campo da IA que permite que computadores analisem e interpretem imagens e vídeos.",
            },
            "viagens": {
                "quais são os documentos necessários para viajar internacionalmente?": "Geralmente é necessário um passaporte válido, visto (dependendo do destino) e, em alguns casos, certificado de vacinação.",
                "qual é o país mais visitado do mundo?": "A França é o país mais visitado do mundo, conhecida por suas atrações como a Torre Eiffel e o Louvre.",
                "o que é uma reserva de hospedagem?": "É o ato de garantir um lugar para se hospedar durante uma viagem, como em hotéis ou pousadas.",
                "como planejar uma viagem?": "Defina o destino, orçamento, meios de transporte, hospedagem e as atividades que deseja realizar.",
                "o que é ecoturismo?": "É um estilo de turismo focado em atividades sustentáveis e em contato com a natureza.",
            },
            "economia_domestica": {
                "como economizar energia em casa?": "Desligue aparelhos quando não estiver usando, troque lâmpadas por LED e use eletrodomésticos eficientes.",
                "como fazer uma lista de compras eficiente?": "Planeje as refeições, revise o que já tem em casa e anote apenas o que precisa.",
                "como reduzir o consumo de água?": "Feche torneiras ao escovar os dentes, use máquinas de lavar na capacidade máxima e reaproveite água da chuva.",
                "o que é orçamento doméstico?": "É o planejamento financeiro para controlar despesas e poupar dinheiro dentro de casa.",
                "como organizar as finanças da família?": "Registre entradas e saídas, priorize necessidades básicas e estabeleça metas de poupança.",
            },
            "hobbies": {
                "o que é fotografia?": "Fotografia é a arte de capturar imagens com câmeras digitais ou analógicas.",
                "o que é jardinagem?": "Jardinagem é o cultivo e cuidado de plantas, flores e hortas.",
                "como começar a pintar?": "Escolha o tipo de tinta (óleo, aquarela ou acrílica), compre pincéis e telas, e comece com exercícios simples.",
                "o que é origami?": "Origami é a arte japonesa de dobrar papel para criar formas e figuras.",
                "o que é colecionismo?": "É o hobby de coletar objetos como moedas, selos, action figures ou antiguidades.",
            },
            "curiosidades_do_corpo_humano": {
                "quantos ossos tem o corpo humano?": "Um adulto tem 206 ossos.",
                "quanto tempo leva para o sangue dar uma volta completa no corpo?": "Cerca de 1 minuto em condições normais.",
                "o que é o maior órgão do corpo humano?": "A pele é o maior órgão do corpo humano.",
                "quantos litros de sangue tem um adulto?": "Um adulto tem entre 4,5 e 6 litros de sangue.",
                "o que são células?": "Células são as unidades básicas que formam todos os seres vivos.",
            },
            "linguas_e_cultura": {
                "quantas letras tem o alfabeto grego?": "O alfabeto grego tem 24 letras.",
                "qual é a língua mais falada no mundo?": "O mandarim é a língua mais falada no mundo em número de falantes nativos.",
                "o que é um dialeto?": "Um dialeto é uma variação regional ou social de uma língua.",
                "como surgiu o português?": "O português surgiu do latim vulgar, trazido pelos romanos à Península Ibérica.",
                "o que significa bilinguismo?": "Bilinguismo é a capacidade de uma pessoa falar fluentemente duas línguas.",
            },
            "historia_da_tecnologia": {
                "quem inventou a eletricidade?": "A eletricidade não foi inventada, mas Benjamin Franklin realizou experimentos importantes no século XVIII.",
                "o que é a revolução digital?": "É o período iniciado na segunda metade do século XX com a popularização dos computadores e da internet.",
                "quem criou o primeiro computador?": "O primeiro computador eletrônico, ENIAC, foi criado por John Presper Eckert e John Mauchly em 1945.",
                "o que é a inteligência artificial?": "É um campo da tecnologia que desenvolve máquinas capazes de realizar tarefas que exigem inteligência humana.",
                "quem inventou o telefone?": "O telefone foi inventado por Alexander Graham Bell em 1876.",
            },
            "curiosidades_cientificas": {
                "por que o gelo flutua na água?": "Porque a densidade do gelo é menor que a densidade da água líquida.",
                "qual é a idade do universo?": "O universo tem aproximadamente 13,8 bilhões de anos.",
                "o que são buracos de minhoca?": "São estruturas teóricas que conectariam diferentes pontos do espaço-tempo.",
                "o que é a teoria do big bang?": "É a teoria que descreve a origem do universo a partir de uma grande explosão há 13,8 bilhões de anos.",
                "o que é um quasar?": "É um objeto extremamente luminoso no centro de galáxias distantes, alimentado por buracos negros supermassivos.",
            },
            "curiosidades_geologicas": {
                "como se formam os vulcões?": "Os vulcões se formam quando o magma do interior da Terra encontra uma abertura na crosta terrestre.",
                "o que são placas tectônicas?": "São grandes blocos que formam a crosta terrestre e se movem sobre o manto.",
                "o que é o núcleo da terra?": "O núcleo é a camada mais interna da Terra, composto principalmente de ferro e níquel.",
                "qual é a maior cordilheira do mundo?": "A Cordilheira dos Andes, na América do Sul, é a mais longa cordilheira continental.",
                "o que são terremotos?": "São vibrações na crosta terrestre causadas pelo movimento das placas tectônicas.",
            },
            "curiosidades_do_universo": {
                "o que é um buraco negro?": "É uma região do espaço com gravidade tão intensa que nem mesmo a luz pode escapar.",
                "qual é a estrela mais próxima da terra?": "A estrela mais próxima da Terra é o Sol.",
                "o que é uma galáxia?": "É um enorme sistema composto de bilhões de estrelas, planetas, gás e poeira, ligados pela gravidade.",
                "o que é a Via Láctea?": "A Via Láctea é a galáxia onde está localizado o Sistema Solar.",
                "o que é um meteoro?": "É um fragmento de rocha ou metal que entra na atmosfera da Terra, criando um rastro luminoso.",
            },
            "fatos_sobre_a_terra": {
                "qual é o diâmetro da terra?": "O diâmetro da Terra é de aproximadamente 12.742 km.",
                "qual é a velocidade de rotação da terra?": "A Terra gira a uma velocidade de aproximadamente 1.670 km/h na linha do equador.",
                "quantos continentes existem?": "Existem sete continentes: África, América do Norte, América do Sul, Antártida, Ásia, Europa e Oceania.",
                "o que é a atmosfera terrestre?": "É a camada de gases que envolve a Terra, composta principalmente de nitrogênio e oxigênio.",
                "o que são fuso horários?": "Fuso horários são divisões do globo terrestre que definem diferentes horários baseados na posição do Sol.",
            },
            "natureza_e_ecossistemas": {
                "o que é uma floresta tropical?": "É um bioma caracterizado por alta biodiversidade e clima quente e úmido.",
                "o que são biomas?": "Biomas são grandes regiões com características climáticas, fauna e flora específicas.",
                "qual é o maior rio do mundo?": "O Rio Amazonas é o maior rio em volume de água e extensão.",
                "o que são ecossistemas?": "São comunidades de seres vivos interagindo com o ambiente não vivo, como água, solo e ar.",
                "o que é biodiversidade?": "É a variedade de espécies vivas em um determinado ecossistema ou no planeta como um todo.",
            },
            "cultura_popular": {
                "quem são os vingadores?": "Os Vingadores são um grupo de super-heróis da Marvel, incluindo personagens como Homem de Ferro, Capitão América e Thor.",
                "o que é star wars?": "Star Wars é uma saga de filmes que mistura ficção científica e fantasia, criada por George Lucas.",
                "quem é o homem-aranha?": "O Homem-Aranha é um super-herói da Marvel, alter ego de Peter Parker, que ganhou poderes após ser picado por uma aranha radioativa.",
                "o que é um anime?": "Anime é uma forma de animação originada no Japão, conhecida por seu estilo artístico único.",
                "quem é harry potter?": "Harry Potter é o protagonista de uma série de livros e filmes criados por J.K. Rowling.",
            },
            "historia_cientifica": {
                "quem foi isaac newton?": "Newton foi um cientista que formulou as leis da gravitação universal e do movimento.",
                "o que é a teoria da relatividade?": "É uma teoria de Albert Einstein que descreve a relação entre espaço, tempo e gravidade.",
                "quem descobriu a penicilina?": "A penicilina foi descoberta por Alexander Fleming em 1928.",
                "quem foi marie curie?": "Marie Curie foi uma cientista pioneira em pesquisas sobre radioatividade e a primeira mulher a ganhar um Nobel.",
                "o que é a tabela periódica?": "É uma organização dos elementos químicos com base em suas propriedades e número atômico.",
            },
            "tecnologia_espacial": {
                "o que é um satélite?": "Um satélite é um objeto que orbita um corpo celeste, como a Terra. Pode ser natural (como a Lua) ou artificial.",
                "o que é a estação espacial internacional?": "É uma estação espacial modular em órbita da Terra, usada para pesquisa científica e cooperação internacional.",
                "quem foi o primeiro homem a pisar na Lua?": "Neil Armstrong foi o primeiro homem a pisar na Lua, em 20 de julho de 1969.",
                "o que é o telescópio hubble?": "O Telescópio Hubble é um observatório espacial que tirou imagens detalhadas do universo desde 1990.",
                "o que são exoplanetas?": "Exoplanetas são planetas que orbitam estrelas fora do nosso Sistema Solar.",
            },
            "historia_do_cinema": {
                "quem inventou o cinema?": "Os irmãos Lumière são creditados como os inventores do cinema, com sua primeira exibição pública em 1895.",
                "qual foi o primeiro filme com som?": "O primeiro filme com som sincronizado foi 'O Cantor de Jazz', lançado em 1927.",
                "o que é hollywood?": "Hollywood é uma região em Los Angeles conhecida como o centro da indústria cinematográfica americana.",
                "quem é alfred hitchcock?": "Alfred Hitchcock foi um diretor de cinema britânico, famoso por filmes de suspense como 'Psicose' e 'Janela Indiscreta'.",
                "o que é um blockbuster?": "É um filme que alcança grande sucesso comercial, geralmente com altos orçamentos e campanhas de marketing.",
            },
            "biologia": {
                "o que é a fotossíntese?": "É o processo pelo qual plantas, algas e algumas bactérias transformam luz solar em energia química.",
                "quantos cromossomos tem o ser humano?": "Os seres humanos têm 46 cromossomos em cada célula somática, organizados em 23 pares.",
                "o que é um ecossistema?": "É um sistema formado por organismos vivos interagindo com o ambiente físico.",
                "o que são mamíferos?": "Mamíferos são animais vertebrados que possuem glândulas mamárias para alimentar seus filhotes.",
                "o que é o DNA?": "DNA, ou ácido desoxirribonucleico, é o material genético que contém as instruções para o funcionamento e desenvolvimento dos seres vivos.",
            },
            "historia_global": {
                "o que foi a primeira guerra mundial?": "Foi um conflito global que durou de 1914 a 1918, envolvendo potências europeias e causando milhões de mortes.",
                "quem foi napoleão bonaparte?": "Napoleão foi um líder militar e imperador da França, conhecido por suas conquistas na Europa.",
                "o que foi a revolução russa?": "A Revolução Russa de 1917 derrubou o czarismo e levou à formação da União Soviética.",
                "o que foi a guerra do vietnã?": "Foi um conflito entre o Vietnã do Norte e do Sul, no qual os Estados Unidos participaram, durando de 1955 a 1975.",
                "o que foi o tratado de versalhes?": "Foi o tratado que encerrou oficialmente a Primeira Guerra Mundial em 1919, impondo duras condições à Alemanha.",
            },
            "economia_global": {
                "o que é globalização?": "Globalização é o processo de integração econômica, social e cultural entre os países.",
                "o que é o FMI?": "O FMI, ou Fundo Monetário Internacional, é uma organização que promove a cooperação econômica global.",
                "o que são criptomoedas?": "São moedas digitais descentralizadas, como Bitcoin, que utilizam blockchain para transações seguras.",
                "o que é PIB per capita?": "É o Produto Interno Bruto dividido pela população de um país, indicando a riqueza média por pessoa.",
                "o que são ações?": "Ações são partes do capital de uma empresa que podem ser compradas e vendidas no mercado financeiro.",
            },
            "fenomenos_climaticos": {
                "o que é el niño?": "El Niño é um fenômeno climático caracterizado pelo aquecimento anormal das águas do Oceano Pacífico.",
                "o que é uma seca?": "É uma condição prolongada de falta de chuva, afetando o abastecimento de água e a agricultura.",
                "o que é um ciclone?": "É uma área de baixa pressão atmosférica com ventos fortes girando em espiral.",
                "o que é a camada de ozônio?": "É uma camada na estratosfera que protege a Terra da radiação ultravioleta do Sol.",
                "o que é aquecimento global?": "É o aumento da temperatura média da Terra devido à emissão de gases do efeito estufa.",
            },
            "saude_e_nutricao": {
                "o que são vitaminas?": "Vitaminas são nutrientes essenciais necessários em pequenas quantidades para o funcionamento do corpo.",
                "o que é proteína?": "Proteína é um macronutriente que ajuda na construção e reparo de tecidos do corpo.",
                "o que é colesterol?": "É uma substância gordurosa encontrada no sangue. O equilíbrio entre colesterol bom (HDL) e ruim (LDL) é importante para a saúde.",
                "como prevenir a obesidade?": "Mantenha uma alimentação equilibrada, pratique exercícios regularmente e evite alimentos ultraprocessados.",
                "o que é uma dieta equilibrada?": "É uma dieta que fornece todos os nutrientes necessários ao corpo nas proporções adequadas.",
            },
            "mitologias_avancadas": {
                "quem foi hércules?": "Hércules é um herói da mitologia grega conhecido por sua força e pelos Doze Trabalhos que realizou.",
                "o que é o ragnarok?": "Ragnarok é o fim do mundo na mitologia nórdica, marcado por uma batalha entre os deuses.",
                "quem foi apolo?": "Apolo é o deus grego do Sol, da música e da profecia.",
                "o que é o olimpo?": "O Monte Olimpo é a morada dos deuses na mitologia grega.",
                "quem é anúbis?": "Anúbis é o deus egípcio responsável por guiar os mortos para o submundo.",
            },
            "tecnologias_do_futuro": {
                "o que é computação quântica?": "Computação quântica utiliza princípios da mecânica quântica para realizar cálculos extremamente complexos.",
                "o que é inteligência artificial geral?": "É um conceito hipotético de IA que pode realizar qualquer tarefa intelectual humana.",
                "o que são carros autônomos?": "São veículos que utilizam sensores e IA para dirigir sem intervenção humana.",
                "o que é a internet das coisas (iot)?": "É a interconexão de dispositivos pela internet, permitindo comunicação e automação.",
                "o que são drones?": "Drones são veículos aéreos não tripulados usados para diversas aplicações, como entregas e monitoramento.",
            },
            "saude_publica": {
                "o que é o SUS?": "O SUS é o Sistema Único de Saúde do Brasil, que oferece acesso universal e gratuito a serviços de saúde.",
                "como prevenir doenças transmissíveis?": "Lave as mãos regularmente, mantenha a vacinação em dia e evite contato com pessoas infectadas.",
                "o que é epidemia?": "É quando uma doença afeta um grande número de pessoas em uma região específica.",
                "o que é pandemia?": "Uma pandemia ocorre quando uma doença se espalha globalmente, afetando vários países ou continentes.",
                "como funciona uma vacina?": "Vacinas estimulam o sistema imunológico a criar defesas contra doenças específicas.",
            },
            "tecnologia_e_ciencia": {
                "o que é nanotecnologia?": "É a ciência que manipula materiais em escala nanométrica, usados em medicina, eletrônicos e energia.",
                "o que é biotecnologia?": "É a aplicação de processos biológicos para desenvolver produtos, como medicamentos e alimentos geneticamente modificados.",
                "o que é energia renovável?": "É energia gerada por fontes que se renovam naturalmente, como solar, eólica e hidrelétrica.",
                "o que é realidade aumentada?": "É uma tecnologia que adiciona elementos virtuais ao mundo real, geralmente visualizados em dispositivos como smartphones.",
                "o que é blockchain?": "Blockchain é um sistema descentralizado de registro de transações, usado principalmente em criptomoedas.",
            },
            "economia_do_dia_a_dia": {
                "como fazer um planejamento financeiro?": "Liste suas receitas e despesas, estabeleça metas e reserve uma parte para poupança.",
                "o que é uma poupança?": "É uma conta bancária que permite guardar dinheiro com rendimentos mensais.",
                "como sair das dívidas?": "Priorize pagar dívidas com juros altos, renegocie prazos e corte gastos desnecessários.",
                "o que é inflação?": "É o aumento generalizado dos preços ao longo do tempo.",
                "como economizar dinheiro?": "Faça um orçamento, evite compras por impulso e priorize necessidades básicas.",
            },
            "educacao_e_aprendizagem": {
                "o que é alfabetização digital?": "É a habilidade de usar ferramentas tecnológicas e acessar informações online de maneira eficiente.",
                "como melhorar a concentração nos estudos?": "Crie um ambiente sem distrações, defina metas claras e faça pausas regulares.",
                "o que é ensino híbrido?": "É um modelo de educação que combina aulas presenciais com atividades online.",
                "o que é gamificação na educação?": "É o uso de elementos de jogos, como recompensas e desafios, para tornar o aprendizado mais envolvente.",
                "o que é um curso técnico?": "É uma formação voltada para o mercado de trabalho, com foco em áreas específicas como eletrônica, informática ou enfermagem.",
            },
            "desenvolvimento_pessoal": {
                "como desenvolver inteligência emocional?": "Aprenda a reconhecer e gerenciar suas emoções, pratique empatia e melhore a comunicação.",
                "o que é produtividade?": "É a capacidade de realizar tarefas de forma eficiente, alcançando resultados com menor esforço.",
                "como criar hábitos saudáveis?": "Defina metas realistas, pratique regularmente e mantenha consistência até que o hábito seja automático.",
                "o que é resiliência?": "É a capacidade de se recuperar rapidamente de adversidades e manter o foco em objetivos.",
                "como lidar com a procrastinação?": "Divida grandes tarefas em etapas menores, elimine distrações e estabeleça prazos claros.",
            },
            "historia_do_brasil": {
                "quando foi proclamada a independência do brasil?": "A independência do Brasil foi proclamada em 7 de setembro de 1822.",
                "o que foi a ditadura militar no brasil?": "Foi um período entre 1964 e 1985 em que o Brasil foi governado por militares, com restrição de direitos civis.",
                "quem foi tiradentes?": "Tiradentes foi um líder da Inconfidência Mineira, movimento que buscava a independência do Brasil no século XVIII.",
                "o que foi o plano real?": "Foi um conjunto de medidas econômicas implementadas em 1994 que estabilizou a inflação no Brasil.",
                "o que foi a abolição da escravatura?": "Foi o processo que encerrou oficialmente a escravidão no Brasil em 13 de maio de 1888.",
            },
            "alimentacao_e_sustentabilidade": {
                "o que é agricultura sustentável?": "É uma forma de cultivo que preserva o meio ambiente e usa recursos de forma responsável.",
                "o que são alimentos orgânicos?": "São alimentos cultivados sem o uso de pesticidas químicos ou fertilizantes sintéticos.",
                "como reduzir o desperdício de alimentos?": "Compre apenas o necessário, armazene adequadamente e reutilize sobras em novas receitas.",
                "o que é dieta vegetariana?": "É uma dieta baseada no consumo de vegetais, excluindo carne e, em alguns casos, produtos de origem animal.",
                "o que são alimentos ultraprocessados?": "São produtos altamente industrializados, com adição de conservantes, corantes e outros ingredientes artificiais.",
            },
            "meio_ambiente_e_conservacao": {
                "o que é reciclagem?": "É o processo de transformar resíduos em novos materiais ou produtos.",
                "como economizar água em casa?": "Conserte vazamentos, reutilize água da chuva e evite desperdícios ao lavar louças e roupas.",
                "o que é desmatamento?": "É a remoção de florestas para dar lugar a atividades humanas, como agricultura ou urbanização.",
                "o que é energia solar?": "É a energia captada do Sol por meio de painéis fotovoltaicos, usada para gerar eletricidade.",
                "como preservar a biodiversidade?": "Proteja habitats naturais, reduza a poluição e apoie práticas sustentáveis.",
            },
            "curiosidades_gerais": {
                "o que é o monte everest?": "É a montanha mais alta do mundo, com 8.848 metros, localizada na fronteira entre Nepal e China.",
                "qual é o maior oceano do mundo?": "O Oceano Pacífico é o maior do mundo, cobrindo cerca de 63 milhões de quilômetros quadrados.",
                "o que é a aurora boreal?": "É um fenômeno natural causado por partículas solares interagindo com a atmosfera terrestre.",
                "o que é o lago baikal?": "É o lago mais profundo do mundo, localizado na Rússia, com 1.642 metros de profundidade.",
                "o que é o deserto do atacama?": "É um dos desertos mais secos do mundo, localizado no norte do Chile.",
            },
            "psicologia_e_mente": {
                "o que é o inconsciente?": "É uma parte da mente que armazena pensamentos e desejos que não estão acessíveis diretamente à consciência.",
                "o que são transtornos de ansiedade?": "São condições de saúde mental caracterizadas por medo e preocupação excessivos.",
                "o que é a pirâmide de maslow?": "É uma teoria que organiza as necessidades humanas em uma hierarquia, desde as básicas até a autorrealização.",
                "o que é psicologia positiva?": "É o estudo científico do bem-estar e das forças que permitem às pessoas prosperar.",
                "o que é empatia?": "Empatia é a capacidade de se colocar no lugar do outro e entender seus sentimentos.",
            },
            "tecnologia_avancada": {
                "o que é a computação em nuvem?": "É um modelo de computação que permite acesso remoto a recursos como armazenamento e processamento por meio da internet.",
                "o que é inteligência artificial?": "É o campo da ciência que desenvolve sistemas capazes de realizar tarefas que normalmente exigiriam inteligência humana.",
                "o que é edge computing?": "É um modelo de computação que processa dados mais próximo da fonte, reduzindo latência e uso de banda.",
                "o que é machine learning?": "É uma subárea da IA que ensina máquinas a aprenderem padrões a partir de dados.",
                "o que é internet das coisas?": "Internet das Coisas (IoT) é a interconexão de dispositivos pela internet, permitindo comunicação e automação.",
            },
            "saude_global": {
                "o que são doenças tropicais?": "São doenças comuns em regiões tropicais, como malária, dengue e febre amarela.",
                "o que é o vírus da zika?": "É um vírus transmitido por mosquitos Aedes aegypti, associado a microcefalia em bebês.",
                "como prevenir doenças cardiovasculares?": "Mantenha uma alimentação saudável, pratique exercícios e evite tabaco e excesso de álcool.",
                "o que é HIV?": "HIV é o vírus da imunodeficiência humana que ataca o sistema imunológico.",
                "o que é saúde mental?": "É o estado de bem-estar emocional, psicológico e social de uma pessoa.",
            },
            "inteligencia_emocional": {
                "o que é inteligência emocional?": "É a capacidade de reconhecer, entender e gerenciar as próprias emoções e as emoções dos outros.",
                "como desenvolver empatia?": "Pratique ouvir ativamente, se coloque no lugar dos outros e busque entender suas perspectivas.",
                "o que é autoconsciência?": "É a habilidade de reconhecer e entender seus próprios estados emocionais.",
                "como lidar com emoções negativas?": "Pratique respiração profunda, reflita sobre as causas e procure técnicas de relaxamento.",
                "o que é resiliência emocional?": "É a capacidade de se adaptar e se recuperar de situações desafiadoras ou traumáticas.",
            },
            "física": {
                "o que é gravidade?": "É a força que atrai dois corpos um ao outro, proporcional às suas massas.",
                "o que é energia cinética?": "É a energia que um corpo possui devido ao seu movimento.",
                "o que é velocidade da luz?": "É a velocidade máxima com que a luz viaja no vácuo, aproximadamente 299.792 km/s.",
                "o que é termodinâmica?": "É o ramo da física que estuda calor, trabalho e energia.",
                "o que é força?": "Força é uma interação que muda o movimento de um objeto ou o deforma.",
            },
            "quimica": {
                "o que é tabela periódica?": "É uma organização dos elementos químicos com base em suas propriedades e número atômico.",
                "o que é reação química?": "É um processo em que substâncias se transformam em novas substâncias.",
                "o que são ácidos e bases?": "Ácidos são substâncias que liberam íons H+ em solução, enquanto bases liberam íons OH-.",
                "o que é química orgânica?": "É o ramo da química que estuda compostos de carbono.",
                "o que são ligações covalentes?": "São ligações químicas em que átomos compartilham elétrons.",
            },
            "historia_moderna": {
                "o que foi a revolução industrial?": "Foi um período entre os séculos XVIII e XIX marcado por avanços tecnológicos e mudanças econômicas e sociais.",
                "quem foi winston churchill?": "Foi o primeiro-ministro britânico durante a Segunda Guerra Mundial, conhecido por sua liderança.",
                "o que foi o nazismo?": "Foi uma ideologia política liderada por Adolf Hitler na Alemanha, caracterizada por autoritarismo e racismo.",
                "o que foi o tratado de versalhes?": "Foi um tratado que encerrou a Primeira Guerra Mundial, impondo condições severas à Alemanha.",
                "o que foi o movimento sufragista?": "Foi o movimento que lutou pelos direitos das mulheres ao voto.",
            },
            "climatologia": {
                "o que é efeito estufa?": "É o fenômeno pelo qual gases na atmosfera aprisionam calor, aquecendo a Terra.",
                "o que são microclimas?": "São variações climáticas em pequenas áreas, como cidades ou florestas.",
                "o que é mudança climática?": "É a alteração no clima global devido a fatores naturais e atividades humanas.",
                "o que são furacões?": "São tempestades tropicais intensas formadas sobre oceanos quentes.",
                "o que é a camada de ozônio?": "É uma camada na atmosfera que protege a Terra dos raios UV do Sol.",
            },
            "literatura": {
                "quem foi machado de assis?": "Foi um dos maiores escritores da literatura brasileira, autor de obras como 'Dom Casmurro'.",
                "o que é um romance?": "É uma narrativa longa que desenvolve personagens e enredo em profundidade.",
                "quem foi william shakespeare?": "Foi um dramaturgo inglês conhecido por peças como 'Romeu e Julieta' e 'Hamlet'.",
                "o que é poesia?": "É uma forma de expressão artística que utiliza linguagem figurada, rima e ritmo.",
                "quem foi clarice lispector?": "Foi uma escritora brasileira famosa por suas obras introspectivas e psicológicas, como 'A Hora da Estrela'.",
            },
            "filosofia_avançada": {
                "o que é o niilismo?": "É uma corrente filosófica que nega valores e significados intrínsecos à existência.",
                "o que é o empirismo?": "É a teoria de que o conhecimento vem principalmente da experiência sensorial.",
                "quem foi kant?": "Immanuel Kant foi um filósofo alemão conhecido por sua teoria do conhecimento e ética.",
                "o que é o existencialismo?": "É uma corrente filosófica que enfatiza a liberdade individual e a responsabilidade sobre as escolhas.",
                "quem foi descartes?": "René Descartes foi um filósofo francês conhecido pela frase 'Penso, logo existo'.",
            },
            "cozinha": {
                "como cozinhar arroz?": "Refogue o arroz em óleo ou azeite, adicione o dobro de água e cozinhe em fogo baixo até secar.",
                "como fazer café?": "Ferva água, coloque o pó de café no filtro e despeje a água lentamente. Sirva e aproveite.",
                "o que é banho-maria?": "É um método de aquecimento indireto, onde o recipiente com alimento é colocado em água quente.",
                "como conservar frutas?": "Armazene frutas maduras na geladeira e as verdes em temperatura ambiente.",
                "como fazer um ovo pochê?": "Quebre o ovo em água quente com vinagre, sem ferver, e cozinhe por 3 minutos.",
            },
            "casa_e_limpeza": {
                "como tirar manchas de roupas?": "Use sabão neutro ou produtos específicos, esfregue delicadamente e lave em água fria.",
                "como limpar vidros?": "Use uma mistura de água com vinagre e seque com um pano limpo ou jornal.",
                "como desentupir uma pia?": "Despeje água quente com bicarbonato de sódio e vinagre; se necessário, use um desentupidor.",
                "como organizar um armário?": "Separe por categorias, dobre as roupas corretamente e use caixas ou organizadores.",
                "como eliminar odores na geladeira?": "Coloque bicarbonato de sódio ou carvão ativado em um recipiente para absorver os cheiros.",
            },
            "moda_e_estilo": {
                "como combinar roupas?": "Escolha uma peça neutra e adicione cores ou estampas em acessórios ou camadas.",
                "como escolher um sapato confortável?": "Experimente no fim do dia, quando os pés estão mais inchados, e prefira materiais macios.",
                "o que é casual chic?": "É um estilo que combina peças descontraídas com itens mais sofisticados, criando um equilíbrio elegante.",
                "como cuidar de roupas de lã?": "Lave à mão ou no ciclo delicado, evite torcer e seque na horizontal.",
                "como usar acessórios?": "Escolha acessórios que complementem seu estilo e evite excessos para não sobrecarregar o visual.",
            },
            "transporte": {
                "como economizar combustível?": "Evite acelerações bruscas, mantenha os pneus calibrados e planeje sua rota para evitar congestionamentos.",
                "como saber se o carro precisa de manutenção?": "Verifique luzes no painel, ruídos incomuns e o manual do veículo para manutenção preventiva.",
                "o que levar em uma viagem longa de carro?": "Itens básicos incluem ferramentas, água, lanches, documentos e um kit de primeiros socorros.",
                "como usar transporte público?": "Consulte os horários e rotas, tenha troco ou passe em mãos e ceda lugar a pessoas prioritárias.",
                "como evitar enjoos em viagens?": "Evite ler durante o trajeto, mantenha o olhar fixo no horizonte e consuma alimentos leves antes de viajar.",
            },
            "bem-estar": {
                "como melhorar a qualidade do sono?": "Mantenha um horário regular para dormir, evite eletrônicos antes de deitar e crie um ambiente escuro e silencioso.",
                "o que fazer para aliviar o estresse?": "Pratique meditação, exercícios físicos, ou hobbies relaxantes como ler ou ouvir música.",
                "como evitar dores nas costas?": "Mantenha uma postura correta, faça alongamentos regulares e evite carregar peso excessivo.",
                "como criar uma rotina matinal saudável?": "Acorde cedo, tome um café da manhã equilibrado, faça exercícios leves e organize suas tarefas do dia.",
                "o que é mindfulness?": "É uma prática de atenção plena, focada no momento presente sem julgamentos.",
            },
            "tecnologia_prática": {
                "como criar uma senha segura?": "Use pelo menos 12 caracteres, incluindo letras maiúsculas, minúsculas, números e símbolos.",
                "como liberar espaço no celular?": "Exclua arquivos desnecessários, limpe o cache dos aplicativos e transfira fotos para a nuvem.",
                "como usar o Google Maps offline?": "Baixe mapas previamente acessando 'Mapas Offline' no aplicativo.",
                "o que fazer se esquecer uma senha?": "Use a opção de recuperação no site ou aplicativo, respondendo perguntas de segurança ou recebendo um código.",
                "como proteger minha privacidade online?": "Use VPN, evite redes públicas não seguras e mantenha antivírus atualizado.",
            },
            "relacionamentos": {
                "como iniciar uma conversa?": "Faça perguntas abertas sobre interesses ou situações comuns e mostre interesse genuíno.",
                "como lidar com conflitos?": "Ouça a outra pessoa com calma, evite acusações e busque uma solução mútua.",
                "como demonstrar empatia?": "Coloque-se no lugar do outro, valide sentimentos e ofereça apoio sem julgamentos.",
                "como manter um relacionamento saudável?": "Comunique-se abertamente, respeite os limites e invista em momentos de qualidade juntos.",
                "como lidar com críticas?": "Receba críticas com mente aberta, avalie se são construtivas e busque melhorar sem se ofender.",
            },
            "cuidados_com_animais": {
                "o que fazer se meu cachorro não quiser comer?": "Verifique se ele está doente, ofereça alimentos diferentes e consulte um veterinário se persistir.",
                "como treinar um gato a usar a caixa de areia?": "Coloque a caixa em um local tranquilo, mostre ao gato e mantenha-a limpa regularmente.",
                "como cuidar de um peixe beta?": "Forneça um aquário limpo, alimente-o com moderação e mantenha a água na temperatura ideal (25-28°C).",
                "quanto exercício meu cachorro precisa?": "Cachorros pequenos precisam de 30-60 minutos diários; raças maiores podem exigir mais.",
                "como saber se meu animal está doente?": "Fique atento a mudanças no apetite, comportamento, fezes ou sinais como vômitos e apatia.",
            },
            "cotidiano": {
                "como economizar no mercado?": "Planeje suas compras com uma lista, evite produtos desnecessários e prefira marcas econômicas.",
                "como evitar atrasos?": "Acorde mais cedo, planeje suas tarefas e use lembretes ou alarmes.",
                "como lidar com vizinhos barulhentos?": "Converse de forma amigável e, se necessário, procure mediação com o síndico ou autoridades locais.",
                "como encontrar um endereço?": "Use aplicativos de mapas como Google Maps ou pergunte a moradores locais.",
                "como cuidar de plantas em casa?": "Regue regularmente, forneça luz adequada e evite encharcar o solo."
                } };